sudo: required
dist: trusty

language: python

python: 
  - "3.5"
  
install: "pip install requests"
install: "pip install neo4j-driver"

services:
  - neo4j
  
  
script: 
  - cd src
  - python uk/ac/ebi/vfb/neo4j/travis_neo_tests/rest_test.py
   



