sudo: required
dist: xenial

before_install:
  - docker run -d --name db -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=2G --env=BACKUPFILE=VFB-KB2 --volume=/Users/davidos:/import/ virtualflybrain/vfb-prod:kb
  - docker run -d --name pdb -p 7475:7474 -p 7688:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=2G --env=BACKUPFILE=VFB-PDB2 --volume=/Users/davidos:/import/ virtualflybrain/vfb-prod:pdb
  - sleep 2m
  - git clone https://github.com/VirtualFlyBrain/VFB_connect.git

services:
  - docker

env:
  - VN="uk.ac.ebi.vfb.neo4j"

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r VFB_connect/requirements.txt
  
script:
  - export PYTHONPATH=$PYTHONPATH":/"$TRAVIS_BUILD_DIR/VFB_connect/src
  - export KB=http://localhost:7474/
  - export PDB=http://localhost:7475/
  - export USR=neo4j
  - export PWD=neo4j
  - export FILEPATH=$TRAVIS_BUILD_DIR/src/
  - export ENDPOINT=$PDB
  - echo -e "travis_fold:start:db-log"
  - curl -sSf -u neo4j:neo4j "http://localhost:7474/db/data/"
  - docker logs --tail 10 db
  - echo -e "travis_fold:end:db-log"
  - echo -e "travis_fold:start:pdb-log"
  - curl -sSf -u neo4j:neo4j "http://localhost:7475/db/data/"
  - docker logs --tail 10 pdb
  - echo -e "travis_fold:end:pdb-log"
  - echo $VN
  - cd src
  - python -m $VN.test.KB_tools_test
  - python -m $VN.test.neo_tools_tests
  - python -m $VN.flybase2neo.test.feature_tools_tests
  - python -m $VN.flybase2neo.test.pub_tools_tests
  - python -m $VN.owl2neo.test.owl2neo_tools_tests
  - python -m $VN.flybase2neo.expression_runner --test http://localhost:7475 neo4j neo4j $TRAVIS_BUILD_DIR/src/ # Really more or an intgration test - consider splitting out.
  - python -m $VN.flybase2neo.add_refs_for_anat http://localhost:7475 neo4j neo4j # Integration test.
  - python -m $VN.neo2neo.expand_xrefs http://localhost:7475 n3o4j



