sudo: required

before_install:
  - mkdir csv_imports
  - docker run -d --name db -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEOREADONLY=false --volume=csv_imports:/import virtualflybrain/docker-vfb-neo4j
  - sleep 30s

services:
  - docker

env:
  - VN="uk.ac.ebi.vfb.neo4j"

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  
script:
  - docker logs db
  - curl -u neo4j:neo4j "http://localhost:7474/db/data/"
  - echo $VN
  - cd src
  - python -m $VN.test.KB_tools_test
  - python -m $VN.test.neo_tools_tests

