sudo: required
dist: xenial

before_install:
  - docker run -d --name db -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEOREADONLY=false --env=NEO4J_dbms_memory_heap_maxSize=1G --volume=$TRAVIS_BUILD_DIR/src/:/import/ virtualflybrain/docker-vfb-neo4j:enterprise 
  - docker run -d --name pdb -p 7475:7474 -p 7688:7687 --env=NEO4J_AUTH=none --env=NEOREADONLY=false --env=NEO4J_CACHE_MEMORY=1G --env=NEO4J_HEAP_MEMORY=2560 --volume=$TRAVIS_BUILD_DIR/src/:/import/ virtualflybrain/docker-vfb-neo4j-productiondb 
  - sleep 50s

services:
  - docker

env:
  - VN="uk.ac.ebi.vfb.neo4j"

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  
script:
  - export KB=http://localhost:7474/
  - export PDB=http://localhost:7475/
  - export USR=neo4j
  - export PWD=neo4j
  - export FILEPATH=$TRAVIS_BUILD_DIR/src/
  - export ENDPOINT=$PDB
  - echo -e "travis_fold:start:db-log"
  - curl -sSf -u neo4j:neo4j "http://localhost:7474/db/data/"
  - docker logs db
  - echo -e "travis_fold:end:db-log"
  - echo -e "travis_fold:start:pdb-log"
  - curl -sSf -u neo4j:neo4j "http://localhost:7475/db/data/"
  - docker logs pdb
  - echo -e "travis_fold:end:pdb-log"
  - echo $VN
  - cd src
  - python -m $VN.test.KB_tools_test
  - python -m $VN.test.neo_tools_tests
  - python -m $VN.flybase2neo.test.feature_tools_tests
  - python -m $VN.flybase2neo.test.pub_tools_tests
  - python -m $VN.flybase2neo.expression_runner --test http://localhost:7475 neo4j neo4j $TRAVIS_BUILD_DIR/src/ # Really more or an intgration test - consider splitting out.
  - python -m $VN.flybase2neo.add_refs_for_anat --test http://localhost:7475 neo4j neo4j # Integration test.
#  - python -m $VN.neo2neo.add_constraints_and_redundant_labels http://localhost:7475 neo4j neo4j # Integration test.


