sudo: required
dist: trusty

language: python

python: 
  - "3.5"
  
install: 
  - "pip install requests"
  - "pip install neo4j-driver"

services:
  - neo4j
 
env:
  - VN="uk.ac.ebi.vfb.neo4j"

  
script: 
  - curl "http://localhost:7474/db/data/"
  - cd src
  - python -m $VN.test.neo_tools_test
   



