sudo: required
dist: trusty

before_install:
  - mkdir csv_imports
  - docker run -d --name db -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_memory_heap_maxSize=3G --volume=csv_imports:/import virtualflybrain/docker-vfb-neo4j:enterprise 
  - docker run -d --name pdb -p 7475:7474 -p 7688:7687 --env=NEO4J_AUTH=none --volume=csv_imports:/import virtualflybrain/docker-vfb-neo4j-productiondb 
  - sleep 50s

services:
  - docker

env:
  - VN="uk.ac.ebi.vfb.neo4j"

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  
script:
  - echo -e "travis_fold:start:db-log"
  - curl -sSf -u neo4j:neo4j "http://localhost:7474/db/data/"
  - docker logs db
  - echo -e "travis_fold:end:db-log"
  - echo -e "travis_fold:start:pdb-log"
  - curl -sSf -u neo4j:neo4j "http://localhost:7475/db/data/"
  - docker logs pdb
  - echo -e "travis_fold:end:pdb-log"
  - echo $VN
  - cd src
  - python -m $VN.test.KB_tools_test
  - python -m $VN.test.neo_tools_tests

