sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y neo4j

services:
  - neo4j

language: python

python: 
  - "3.5"
  
install: 
  - "pip install requests"
  - "pip install neo4j-driver"
 
env:
  - VN="uk.ac.ebi.vfb.neo4j"

  
script: 
  - curl -u neo4j:neo4j "http://localhost:7474/db/data/"
  - echo $VN
  - cd src
  - python -m $VN.test.neo_tools_tests
   



