sudo: required
dist: trusty

before_install:
  - docker run --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data neo4j:enterprise
  - sleep 5m

services:
  - docker

env:
  - VN="uk.ac.ebi.vfb.neo4j"

script: 
  - docker build -t virtualflybrain/neo4j-travis-test github.com/Robbie1977/Docker-VFB_neo4j-Python3
  - docker run -i -t virtualflybrain/neo4j-travis-test python3 -m $VN.test.neo_tools_tests



