sudo: required
dist: xenial

before_install:
  - git clone https://github.com/VirtualFlyBrain/VFB_connect.git

services:
  - docker

env:
  - VN="uk.ac.ebi.vfb.neo4j"

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r VFB_connect/requirements.txt
  
before_script:
  - export PYTHONPATH=$PYTHONPATH":/"$TRAVIS_BUILD_DIR/VFB_connect/src
  - export KB=http://localhost:7474
  - export PDB=http://localhost:7474
  - export USR=neo4j
  - export PWD=neo4j
  - export FILEPATH=$TRAVIS_BUILD_DIR/src/
  - export ENDPOINT=$PDB
  - export LANDING_PAGE=$ENDPOINT/db/data/
  - Test () { export http_status=$(curl -s -i $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'}); echo "Returned status \"$http_status\""; if [ "$http_status" != "200" ]; then echo "Waiting for neo4j to finish loading..."; iterations=$((iterations+1)); if [ "$iterations" != "100" ]; then sleep 60; Test; fi; else echo "$(date) - connected successfully"; fi; }
  
script:
  - echo $VN
  - cd src
  - docker run -d --name kb -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=2G --volume=$TRAVIS_BUILD_DIR/src/:/import/ virtualflybrain/vfb-prod
  - Test
  - sleep 50s
  - python -m $VN.test.KB_tools_test
  - docker stop kb
  - docker run -d --name pdb -p 7474:7475 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=2G --env=BACKUPFILE=VFB-PDB2 --volume=$TRAVIS_BUILD_DIR/src/:/import/ virtualflybrain/vfb-prod:pdb
  - Test
  - sleep 50s
  - python -m $VN.test.neo_tools_tests
  - python -m $VN.flybase2neo.test.feature_tools_tests
  - python -m $VN.flybase2neo.test.pub_tools_tests
  - python -m $VN.owl2neo.test.owl2neo_tools_tests
  - python -m $VN.flybase2neo.expression_runner --test $PDB $USR $PWD $TRAVIS_BUILD_DIR/src/ # Really more or an intgration test - consider splitting out.
  - python -m $VN.flybase2neo.add_refs_for_anat --test $PDB $USR $PWD # Integration test.
  - python -m $VN.neo2neo.expand_xrefs $PDB $USR $PWD
  - python -m $VN.flybase2neo.import_pub_data --test $PDB $USR $PWD



