# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Start databases
      run: |
        docker run -d --name db -p 7474:7474 -p 7687:7687 --env=NEO4J_AUTH=none --env=NEOREADONLY=false --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=1G --volume=$(pwd)/src/:/import/ virtualflybrain/docker-neo4j-knowledgebase
        docker run -d --name pdb -p 7475:7474 -p 7688:7687 --env=NEO4J_AUTH=none --env=NEOREADONLY=false --env=NEO4J_dbms_read__only=false --env=NEO4J_dbms_memory_heap_maxSize=1G --env=NEO4J_HEAP_MEMORY=2560 --volume=$(pwd)/src/:/import/ virtualflybrain/docker-vfb-neo4j-productiondb:pipeline2
        sleep 50s
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install VFBconnect
      run: |
        git clone https://github.com/VirtualFlyBrain/VFB_connect.git
        pip install -r VFB_connect/requirements.txt
    
    - name: Run Tests
      run: |
        export VN="uk.ac.ebi.vfb.neo4j"
        export PYTHONPATH=$PYTHONPATH":/"$TRAVIS_BUILD_DIR/VFB_connect/src
        export KB=http://localhost:7474/
        export PDB=http://localhost:7475/
        export USR=neo4j
        export PWD=neo4j
        export FILEPATH=$TRAVIS_BUILD_DIR/src/
        export ENDPOINT=$PDB
        echo -e "travis_fold:start:db-log"
        curl -sSf -u neo4j:neo4j "http://localhost:7474/db/data/"
        docker logs db
        echo -e "travis_fold:end:db-log"
        echo -e "travis_fold:start:pdb-log"
        curl -sSf -u neo4j:neo4j "http://localhost:7475/db/data/"
        docker logs pdb
        echo -e "travis_fold:end:pdb-log"
        echo $VN
        cd src
        python -m $VN.test.KB_tools_test
        python -m $VN.test.neo_tools_tests
        python -m $VN.flybase2neo.test.feature_tools_tests
        python -m $VN.flybase2neo.test.pub_tools_tests
        python -m $VN.flybase2neo.expression_runner --test http://localhost:7475 neo4j neo4j $TRAVIS_BUILD_DIR/src/ # Really more or an intgration test - consider splitting out.
        python -m $VN.flybase2neo.add_refs_for_anat http://localhost:7475 neo4j neo4j # Integration test.
    
    
    - name: Test with pytest
      run: |
        pytest
    
    
